# Generated by Django 5.2.5 on 2025-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商家名稱')),
                ('domain', models.URLField(blank=True, help_text='用於 Chrome 擴展識別', verbose_name='網域名稱')),
                ('category', models.CharField(choices=[('ONLINE', '電商'), ('SUPER', '超市'), ('DEPT', '百貨公司'), ('CVS', '便利商店'), ('GAS', '加油站'), ('REST', '餐廳'), ('ENT', '休閒娛樂'), ('TRANS', '交通運輸'), ('HOSP', '醫療院所'), ('EDU', '教育學習'), ('TEL', '電信通訊'), ('INS', '保險'), ('UTIL', '公用事業'), ('STREAM', '串流平台'), ('TRA', '旅遊/訂房'), ('OTHER', '其他')], default='OTHER', max_length=10, verbose_name='主要分類')),
                ('secondary_category', models.CharField(blank=True, max_length=30, verbose_name='次要分類')),
                ('merchant_code', models.CharField(blank=True, help_text='與銀行系統對接用', max_length=10, unique=True, verbose_name='商家代碼')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'merchants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['domain'], name='merchants_domain_idx'), models.Index(fields=['category'], name='merchants_category_idx')],
            },
        ),
    ]
