# Generated by Django 5.2.5 on 2025-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ['name'], 'verbose_name': 'Merchant', 'verbose_name_plural': 'Merchants'},
        ),
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.CharField(choices=[('ONLINE', '電商'), ('SUPER', '超市'), ('DEPT', '百貨公司'), ('CVS', '便利商店'), ('GAS', '加油站'), ('REST', '餐廳'), ('ENT', '休閒娛樂'), ('TRANS', '交通運輸'), ('HOSP', '醫療院所'), ('EDU', '教育學習'), ('TEL', '電信通訊'), ('INS', '保險'), ('UTIL', '公用事業'), ('STREAM', '串流平台'), ('TRA', '旅遊/訂房'), ('OTHER', '其他')], default='OTHER', max_length=10, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='domain',
            field=models.URLField(blank=True, help_text='用於 Chrome 擴展識別', verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_code',
            field=models.CharField(blank=True, help_text='與銀行系統對接用', max_length=10, unique=True, verbose_name='Merchant Code'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Merchant Name'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='secondary_category',
            field=models.CharField(blank=True, max_length=30, verbose_name='Second Category'),
        ),
    ]
