# Generated by Django 5.2.5 on 2025-09-03 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.DecimalField(decimal_places=3, help_text='分析所花費的總時間（秒）', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='分析總時間')),
                ('analyzed_count', models.PositiveIntegerField(help_text='總共分析的項目數量', verbose_name='分析數量')),
                ('average_time', models.DecimalField(decimal_places=3, help_text='每個項目的平均分析時間（秒）', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='平均分析時間')),
                ('errors', models.JSONField(blank=True, default=dict, help_text='分析過程中的錯誤資訊', verbose_name='錯誤資訊')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析日期')),
            ],
            options={
                'verbose_name': '分析統計',
                'verbose_name_plural': '分析統計',
                'db_table': 'analysis_statistics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analysis_stats_date_idx')],
            },
        ),
    ]
