# Generated by Django 5.2.5 on 2025-08-25 05:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_alter_bank_options_alter_bank_code_and_more'),
        ('cards', '0002_alter_creditcard_options_alter_creditcard_annual_fee_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('merchants', '0002_alter_merchant_options_alter_merchant_category_and_more'),
        ('rewards', '0002_alter_merchantreward_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='規則名稱', max_length=100, verbose_name='Rule Name')),
                ('description', models.TextField(blank=True, help_text='規則描述', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='啟用狀態', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'NLP 驗證規則',
                'verbose_name_plural': 'NLP 驗證規則',
                'db_table': 'nlp_validation_rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValidationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='會話ID', max_length=50, unique=True, verbose_name='Session ID')),
                ('session_type', models.CharField(choices=[('MANUAL', '手動觸發'), ('SCHEDULED', '排程執行'), ('AUTO', '自動觸發'), ('API', 'API 呼叫')], default='MANUAL', help_text='會話類型', max_length=10, verbose_name='Session Type')),
                ('name', models.CharField(help_text='會話名稱', max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('RUNNING', '執行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗'), ('CANCELLED', '已取消')], default='RUNNING', help_text='會話狀態', max_length=10, verbose_name='Status')),
                ('total_items', models.PositiveIntegerField(default=0, help_text='總處理項目數', verbose_name='Total Items')),
                ('completed_items', models.PositiveIntegerField(default=0, help_text='已完成項目數', verbose_name='Completed Items')),
                ('failed_items', models.PositiveIntegerField(default=0, help_text='失敗項目數', verbose_name='Failed Items')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='開始時間', verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成時間', null=True, verbose_name='Completed At')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='觸發者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Triggered By')),
            ],
            options={
                'verbose_name': 'NLP 驗證會話',
                'verbose_name_plural': 'NLP 驗證會話',
                'db_table': 'nlp_validation_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='物件ID (備用)', null=True, verbose_name='Object ID')),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('RUNNING', '執行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], default='PENDING', help_text='執行狀態', max_length=10, verbose_name='Status')),
                ('result_type', models.CharField(choices=[('PASS', '通過'), ('WARNING', '警告'), ('ERROR', '錯誤'), ('INFO', '資訊')], help_text='結果類型', max_length=10, verbose_name='Result Type')),
                ('score', models.DecimalField(blank=True, decimal_places=3, help_text='驗證分數/信心度 (0-1)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Score')),
                ('passed', models.BooleanField(default=False, help_text='是否通過', verbose_name='Passed')),
                ('message', models.TextField(blank=True, help_text='驗證訊息', verbose_name='Message')),
                ('details', models.JSONField(default=dict, help_text='詳細結果 - 存放提取的信用卡資訊\n        預計格式: {\n            "extracted_info": {\n                "foreign_cashback": 2.8,\n                "merchant_momo": 5.3,\n                "annual_fee": 2000\n            },\n            "original_text": "海外消費2.8%回饋，momo購物5.3%",\n            "confidence_scores": {\n                "foreign_cashback": 0.95,\n                "momo": 0.87\n            }\n        }', verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='建立時間', verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, help_text='開始時間', null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成時間', null=True, verbose_name='Completed At')),
                ('bank', models.ForeignKey(blank=True, help_text='關聯銀行', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='banks.bank', verbose_name='Bank')),
                ('card', models.ForeignKey(blank=True, help_text='關聯信用卡', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='cards.creditcard', verbose_name='Credit Card')),
                ('content_type', models.ForeignKey(blank=True, help_text='內容類型 (備用)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('merchant', models.ForeignKey(blank=True, help_text='關聯商家', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='merchants.merchant', verbose_name='Merchant')),
                ('reward_category', models.ForeignKey(blank=True, help_text='關聯回饋分類', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='rewards.rewardcategory', verbose_name='Reward Category')),
                ('rule', models.ForeignKey(help_text='驗證規則', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='nlp_validation.validationrule', verbose_name='Validation Rule')),
                ('session', models.ForeignKey(blank=True, help_text='驗證會話', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='nlp_validation.validationsession', verbose_name='Validation Session')),
            ],
            options={
                'verbose_name': 'NLP 驗證結果',
                'verbose_name_plural': 'NLP 驗證結果',
                'db_table': 'nlp_validation_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['-started_at'], name='sessions_started_idx'),
        ),
        migrations.AddIndex(
            model_name='validationsession',
            index=models.Index(fields=['status'], name='sessions_status_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['rule', '-created_at'], name='results_rule_date_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['status'], name='results_status_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['result_type'], name='results_type_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['content_type', 'object_id'], name='results_content_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['passed'], name='results_passed_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['bank'], name='results_bank_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['card'], name='results_card_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['merchant'], name='results_merchant_idx'),
        ),
        migrations.AddIndex(
            model_name='validationresult',
            index=models.Index(fields=['reward_category'], name='results_reward_idx'),
        ),
    ]
