# Generated by Django 5.2.5 on 2025-09-05 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisstatistics',
            name='analyzed_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='analysisstatistics',
            name='average_time',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='analysisstatistics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analysisstatistics',
            name='errors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='analysisstatistics',
            name='total_time',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
