# Generated by Django 5.2.5 on 2025-08-21 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0002_alter_bank_options_alter_bank_code_and_more'),
        ('cards', '0002_alter_creditcard_options_alter_creditcard_annual_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Crawled Content')),
                ('url', models.CharField(verbose_name='Crawled Website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards_crawled_data', to='banks.bank', verbose_name='Issuing Bank')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_data', to='cards.creditcard', verbose_name='Credit Card')),
            ],
            options={
                'verbose_name': 'Crawled Card',
                'verbose_name_plural': 'Crawled Cards',
                'db_table': 'crawler_data',
            },
        ),
    ]
