# Generated by Django 5.2.5 on 2025-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='card_img',
            field=models.URLField(blank=True, null=True, verbose_name='Card Image'),
        ),
    ]
