# Generated by Django 5.2.5 on 2025-08-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawleddata',
            old_name='name',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='crawleddata',
            name='bank',
        ),
        migrations.AlterField(
            model_name='crawleddata',
            name='url',
            field=models.URLField(verbose_name='Crawled Website'),
        ),
    ]
