# Generated by Django 5.2.5 on 2025-09-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_crawler', '0002_crawleddata_card_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Total Time')),
                ('total_cards', models.IntegerField(verbose_name='Total Cards')),
                ('average_time', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Average Time')),
                ('errors', models.JSONField(verbose_name='Failed Cards')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
