# Generated by Django 5.2.5 on 2025-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "card_crawler",
            "0002_rename_name_crawleddata_card_remove_crawleddata_bank_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawleddata",
            name="url",
            field=models.URLField(default=None, verbose_name="Crawled Website"),
        ),
    ]
