# Generated by Django 5.2.5 on 2025-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("card_crawler", "0003_crawleddata_url_domain_alter_crawleddata_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawleddata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
    ]
