# Generated by Django 5.2.5 on 2025-08-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_crawler', '0004_crawleddata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawleddata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='crawleddata',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
