# Generated by Django 5.2.5 on 2025-08-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_crawler', '0005_crawleddata_deleted_at_crawleddata_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawleddata',
            name='card',
        ),
    ]
