# Generated by Django 5.2.5 on 2025-08-20 04:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_alter_creditcard_options_alter_creditcard_annual_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_reward_type', models.CharField(choices=[('CASHBACK', '現金回饋'), ('POINTS', '紅利點數'), ('LINEPAY', 'Line Pay 點數'), ('MIXED', '不限制')], default='CASHBACK', max_length=20, verbose_name='Preferred Reward Type')),
                ('monthly_spending', models.DecimalField(blank=True, decimal_places=2, help_text='用於個人化推薦', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monthly Average Spending')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='用戶自定義的卡片名稱', max_length=50, verbose_name='Card Nickname')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('is_primary', models.BooleanField(default=False, help_text='用戶的主要推薦卡片', verbose_name='Primary Card')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cards.creditcard', verbose_name='Credit Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Card',
                'verbose_name_plural': 'User Cards',
                'db_table': 'user_cards',
                'ordering': ['-is_primary', '-added_date'],
                'indexes': [models.Index(fields=['user', 'is_primary'], name='user_cards_primary_idx'), models.Index(fields=['user', 'is_active'], name='user_cards_active_idx')],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
