# Generated by Django 5.2.5 on 2025-09-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='usercard',
            options={'ordering': ['-added_date'], 'verbose_name': 'User Card', 'verbose_name_plural': 'User Cards'},
        ),
        migrations.AlterField(
            model_name='usercard',
            name='nickname',
            field=models.CharField(blank=True, help_text='用戶自定義的卡片名稱', max_length=50, null=True, verbose_name='Card Nickname'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
