# Generated by Django 5.2.5 on 2025-09-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='card_number_encrypted',
            field=models.TextField(blank=True, help_text='加密後的信用卡卡號', null=True, verbose_name='Encrypted Card Number'),
        ),
    ]
