# Generated by Django 5.2.5 on 2025-08-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usercard_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
