# Generated by Django 5.2.5 on 2025-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_user_alter_usercard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='用戶收藏的卡片', verbose_name='Favorite Card'),
        ),
    ]
