# Generated by Django 5.2.5 on 2025-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='銀行名稱')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='銀行代碼')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('website_url', models.URLField(blank=True, verbose_name='官方網站')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '銀行',
                'verbose_name_plural': '銀行',
                'db_table': 'banks',
                'ordering': ['name'],
            },
        ),
    ]
