# Generated by Django 5.2.5 on 2025-08-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
