# Generated by Django 5.2.5 on 2025-08-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_options_alter_bank_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo_url',
            field=models.URLField(null=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='website_url',
            field=models.URLField(null=True, verbose_name='URL'),
        ),
    ]
