# Generated by Django 5.2.5 on 2025-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_logo_url_alter_bank_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
