# Generated by Django 5.2.5 on 2025-09-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlp_category', models.CharField(max_length=50, verbose_name='NLP分類')),
                ('nlp_scope', models.CharField(max_length=50, verbose_name='NLP範圍')),
                ('extracted_sentence', models.TextField(verbose_name='提取句子')),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='信心度')),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='最低回饋率')),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='最高回饋率')),
                ('reward_type', models.CharField(max_length=20, verbose_name='回饋類型')),
                ('status', models.CharField(choices=[('PENDING', '待審核'), ('REVIEWING', '審核中'), ('APPROVED', '已通過'), ('REJECTED', '已拒絕')], default='PENDING', max_length=10, verbose_name='審核狀態')),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='軟刪除時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_rewards', to='cards.creditcard', verbose_name='信用卡')),
            ],
            options={
                'verbose_name': '待審核回饋規則',
                'verbose_name_plural': '待審核回饋規則',
                'db_table': 'pending_rewards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='pending_rewards_status_idx'), models.Index(fields=['card'], name='pending_rewards_card_idx'), models.Index(fields=['-created_at'], name='pending_rewards_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='例如：餐廳、加油站', max_length=50, verbose_name='消費類別')),
                ('scope', models.CharField(help_text='例如：速食、一般餐廳', max_length=50, verbose_name='消費種類')),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, help_text='1.00 代表 1%', max_digits=4, null=True, verbose_name='最低回饋率')),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, help_text='5.00 代表 5%', max_digits=4, null=True, verbose_name='最高回饋率')),
                ('reward_type', models.CharField(help_text='例如：現金回饋、紅利點數', max_length=20, verbose_name='回饋類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='cards.creditcard', verbose_name='信用卡')),
            ],
            options={
                'verbose_name': '回饋分類規則',
                'verbose_name_plural': '回饋分類規則',
                'db_table': 'reward_categories',
                'ordering': ['card', '-max_rate'],
                'indexes': [models.Index(fields=['card', 'category'], name='rewards_card_category_idx'), models.Index(fields=['is_active'], name='rewards_active_idx'), models.Index(fields=['min_rate', 'max_rate'], name='rewards_rate_range_idx')],
                'unique_together': {('card', 'category', 'scope')},
            },
        ),
    ]
