# Generated by Django 5.2.5 on 2025-09-02 07:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ONLINE', '電商'), ('SUPER', '超市'), ('DEPT', '百貨公司'), ('CVS', '便利商店'), ('GAS', '加油站'), ('REST', '餐廳'), ('ENT', '休閒娛樂'), ('TRANS', '交通運輸'), ('HOSP', '醫療院所'), ('EDU', '教育學習'), ('TEL', '電信通訊'), ('INS', '保險'), ('UTIL', '公用事業'), ('STREAM', '串流平台'), ('TRA', '旅遊/訂房'), ('OTHER', '其他')], max_length=20, verbose_name='Spending Category')),
                ('rate', models.DecimalField(decimal_places=2, help_text='百分比，例如 3.0 表示 3%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reward Rate')),
                ('reward_type', models.CharField(choices=[('CASHBACK', '現金回饋'), ('POINTS', '紅利點數'), ('LINEPAY', 'Line Pay 點數'), ('MILES', '哩程'), ('OTHER', '其他')], default='CASHBACK', max_length=20, verbose_name='Reward Type')),
                ('points_value', models.DecimalField(blank=True, decimal_places=3, help_text='1點等於多少元，例如 0.5 表示 1點=0.5元', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points Value')),
                ('max_spending', models.DecimalField(blank=True, decimal_places=2, help_text='超過此金額的消費不給回饋或降級回饋', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Reward Spending')),
                ('is_rotating', models.BooleanField(default=False, help_text='是否為季度輪替回饋', verbose_name='Is Rotating')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('requires_activation', models.BooleanField(default=False, help_text='是否需要事先登錄才能享有回饋', verbose_name='Requires Activation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='cards.creditcard', verbose_name='Credit Card')),
            ],
            options={
                'verbose_name': 'Reward Category',
                'verbose_name_plural': 'Reward Categories',
                'db_table': 'reward_categories',
                'ordering': ['card', '-rate'],
                'indexes': [models.Index(fields=['card', 'category'], name='rewards_card_category_idx'), models.Index(fields=['start_date', 'end_date'], name='rewards_date_range_idx')],
                'unique_together': {('card', 'category', 'start_date')},
            },
        ),
    ]
