# Generated by Django 5.2.5 on 2025-09-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingreward',
            name='confidence',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='信心度'),
        ),
    ]
