# Generated by Django 5.2.5 on 2025-09-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlp_category', models.CharField(max_length=50, verbose_name='NLP分類')),
                ('nlp_scope', models.CharField(max_length=50, verbose_name='NLP範圍')),
                ('extracted_sentence', models.TextField(verbose_name='提取句子')),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='信心度')),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='最低回饋率')),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='最高回饋率')),
                ('reward_type', models.CharField(max_length=20, verbose_name='回饋類型')),
                ('status', models.CharField(choices=[('PENDING', '待審核'), ('APPROVED', '已通過'), ('REJECTED', '已拒絕')], default='PENDING', max_length=10, verbose_name='審核狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_rewards', to='cards.creditcard', verbose_name='信用卡')),
            ],
            options={
                'verbose_name': '待審核回饋規則',
                'verbose_name_plural': '待審核回饋規則',
                'db_table': 'pending_rewards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='pending_rewards_status_idx'), models.Index(fields=['card'], name='pending_rewards_card_idx'), models.Index(fields=['-created_at'], name='pending_rewards_date_idx')],
            },
        ),
    ]
