# Generated by Django 5.2.5 on 2025-08-20 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_creditcard_options_alter_creditcard_annual_fee_and_more'),
        ('merchants', '0002_alter_merchant_options_alter_merchant_category_and_more'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchantreward',
            options={'ordering': ['card', 'merchant'], 'verbose_name': 'Merchant Special Reward', 'verbose_name_plural': 'Merchant Special Rewards'},
        ),
        migrations.AlterModelOptions(
            name='rewardcategory',
            options={'ordering': ['card', '-rate'], 'verbose_name': 'Reward Category', 'verbose_name_plural': 'Reward Categories'},
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_rewards', to='cards.creditcard', verbose_name='Credit Card'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='category',
            field=models.ForeignKey(help_text='此特殊規則會覆蓋對應的分類回饋', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_overrides', to='rewards.rewardcategory', verbose_name='Corresponding Reward Category'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='is_promotional',
            field=models.BooleanField(default=False, help_text='是否為限時促銷活動', verbose_name='Promotional Campaign'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='max_spending',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Merchant Reward Amount'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='merchants.merchant', verbose_name='Merchant'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='points_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='1點等於多少元，例如 0.5 表示 1點=0.5元', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points Value'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='覆蓋原分類回饋率，留空則使用分類回饋率', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reward Rate'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='reward_type',
            field=models.CharField(blank=True, choices=[('CASHBACK', '現金回饋'), ('POINTS', '紅利點數'), ('LINEPAY', 'Line Pay 點數'), ('MILES', '哩程'), ('OTHER', '其他')], help_text='留空則使用分類設定', max_length=20, verbose_name='Reward Type'),
        ),
        migrations.AlterField(
            model_name='merchantreward',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='cards.creditcard', verbose_name='Credit Card'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='category',
            field=models.CharField(choices=[('ONLINE', '電商'), ('SUPER', '超市'), ('DEPT', '百貨公司'), ('CVS', '便利商店'), ('GAS', '加油站'), ('REST', '餐廳'), ('ENT', '休閒娛樂'), ('TRANS', '交通運輸'), ('HOSP', '醫療院所'), ('EDU', '教育學習'), ('TEL', '電信通訊'), ('INS', '保險'), ('UTIL', '公用事業'), ('STREAM', '串流平台'), ('TRA', '旅遊/訂房'), ('OTHER', '其他')], max_length=20, verbose_name='Spending Category'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='is_rotating',
            field=models.BooleanField(default=False, help_text='是否為季度輪替回饋', verbose_name='Is Rotating'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='max_spending',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='超過此金額的消費不給回饋或降級回饋', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Reward Spending'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='points_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='1點等於多少元，例如 0.5 表示 1點=0.5元', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points Value'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='百分比，例如 3.0 表示 3%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reward Rate'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='requires_activation',
            field=models.BooleanField(default=False, help_text='是否需要事先登錄才能享有回饋', verbose_name='Requires Activation'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='reward_type',
            field=models.CharField(choices=[('CASHBACK', '現金回饋'), ('POINTS', '紅利點數'), ('LINEPAY', 'Line Pay 點數'), ('MILES', '哩程'), ('OTHER', '其他')], default='CASHBACK', max_length=20, verbose_name='Reward Type'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
