# Generated by Django 5.2.5 on 2025-08-19 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='信用卡名稱')),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='年費')),
                ('signup_bonus', models.IntegerField(default=0, help_text='新戶禮金額或點數', validators=[django.core.validators.MinValueValidator(0)], verbose_name='新戶禮')),
                ('credit_limit_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低額度')),
                ('credit_limit_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最高額度')),
                ('apr_min', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='最低利率')),
                ('apr_max', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='最高利率')),
                ('foreign_transaction_fee', models.DecimalField(decimal_places=2, default=0, help_text='百分比，例如 1.5 表示 1.5%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='海外交易手續費')),
                ('card_network', models.CharField(choices=[('VISA', 'Visa'), ('MC', 'MasterCard'), ('JCB', 'JCB'), ('AMEX', 'American Express'), ('UP', '銀聯')], max_length=20, verbose_name='卡片網路')),
                ('card_type', models.CharField(choices=[('CLASSIC', '一般卡'), ('GOLD', '金卡'), ('PLATINUM', '白金卡'), ('INFINITE', '無限卡'), ('TITANIUM', '鈦金卡'), ('WORLD', '世界卡'), ('SIGNATURE', '御璽卡'), ('BUSINESS', '商務卡'), ('SIGBUSINESS', '商務御璽卡')], max_length=20, verbose_name='卡片等級')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='banks.bank', verbose_name='發卡銀行')),
            ],
            options={
                'verbose_name': '信用卡',
                'verbose_name_plural': '信用卡',
                'db_table': 'credit_cards',
                'ordering': ['bank__name', 'name'],
                'indexes': [models.Index(fields=['bank', 'is_active'], name='cards_bank_active_idx'), models.Index(fields=['card_network'], name='cards_network_idx'), models.Index(fields=['card_type'], name='cards_type_idx')],
            },
        ),
    ]
