# Generated by Django 5.2.5 on 2025-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='信用卡名稱')),
                ('bank', models.CharField(max_length=50, verbose_name='銀行名稱')),
                ('foreign_transaction_fee', models.DecimalField(blank=True, decimal_places=2, help_text='百分比，例如 1.5 表示 1.5%', max_digits=4, null=True, verbose_name='Foreign Transaction Fee')),
                ('card_network', models.CharField(blank=True, choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('JCB', 'JCB'), ('美國運通 AMEX', '美國運通'), ('銀聯', '銀聯')], max_length=20, null=True, verbose_name='Card Network')),
                ('card_type', models.CharField(blank=True, choices=[('CLASSIC', '一般卡'), ('GOLD', '金卡'), ('PLATINUM', '白金卡'), ('INFINITE', '無限卡'), ('TITANIUM', '鈦金卡'), ('WORLD', '世界卡'), ('SIGNATURE', '御璽卡'), ('BUSINESS', '商務卡'), ('SIGBUSINESS', '商務御璽卡')], max_length=20, null=True, verbose_name='Card Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'credit_cards',
                'ordering': ['bank', 'name'],
                'indexes': [models.Index(fields=['bank', 'is_active'], name='cards_bank_active_idx'), models.Index(fields=['card_network'], name='cards_network_idx'), models.Index(fields=['card_type'], name='cards_type_idx')],
            },
        ),
    ]
