# Generated by Django 5.2.5 on 2025-08-20 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_options_alter_bank_code_and_more'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['bank__name', 'name'], 'verbose_name': 'Credit Card', 'verbose_name_plural': 'Credit Cards'},
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Annual Fee'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='apr_max',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum APR'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='apr_min',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum APR'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='banks.bank', verbose_name='Issuing Bank'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_network',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MC', 'MasterCard'), ('JCB', 'JCB'), ('AMEX', 'American Express'), ('UP', '銀聯')], max_length=20, verbose_name='Card Network'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('CLASSIC', '一般卡'), ('GOLD', '金卡'), ('PLATINUM', '白金卡'), ('INFINITE', '無限卡'), ('TITANIUM', '鈦金卡'), ('WORLD', '世界卡'), ('SIGNATURE', '御璽卡'), ('BUSINESS', '商務卡'), ('SIGBUSINESS', '商務御璽卡')], max_length=20, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_limit_max',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Credit Limit'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='credit_limit_min',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Credit Limit'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='foreign_transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='百分比，例如 1.5 表示 1.5%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Foreign Transaction Fee'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='signup_bonus',
            field=models.IntegerField(default=0, help_text='新戶禮金額或點數', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sign Up Bonus'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
