# Generated by Django 5.2.5 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='bank',
            field=models.CharField(max_length=15, verbose_name='銀行名稱'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name',
            field=models.CharField(max_length=50, verbose_name='信用卡名稱'),
        ),
    ]
