# Generated by Django 5.2.5 on 2025-09-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='bank',
            field=models.CharField(choices=[('滙豐', '滙豐'), ('中國信託', '中國信託'), ('國泰', '國泰'), ('玉山', '玉山'), ('台新', '台新'), ('富邦', '富邦'), ('第一', '第一'), ('合庫', '合庫'), ('兆豐', '兆豐'), ('永豐', '永豐'), ('遠東', '遠東'), ('凱基', '凱基'), ('聯邦', '聯邦'), ('星展', '星展'), ('樂天', '樂天'), ('彰化', '彰化'), ('華南', '華南'), ('新光', '新光'), ('上海商銀', '上海商銀'), ('美國運通', '美國運通'), ('渣打', '渣打'), ('陽信', '陽信'), ('LINE Bank', 'Linebank'), ('將來', '將來'), ('元大', '元大'), ('台中銀', '台中銀'), ('王道', '王道')], max_length=50, verbose_name='銀行名稱'),
        ),
    ]
