# Generated by Django 5.2.5 on 2025-09-21 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_creditcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='信用卡圖片'),
        ),
    ]
