# Generated by Django 5.2.5 on 2025-08-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_creditcard_apr_max_remove_creditcard_apr_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='annual_fee',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='signup_bonus',
        ),
    ]
