# Generated by Django 5.2.5 on 2025-09-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_creditcard_bank_alter_creditcard_name'),
        ('cards', '0003_alter_creditcard_bank'),
    ]

    operations = [
    ]
