# Generated by Django 5.2.5 on 2025-08-20 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_alter_creditcard_options_alter_creditcard_annual_fee_and_more'),
        ('merchants', '0002_alter_merchant_options_alter_merchant_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transaction Amount')),
                ('reward_earned', models.DecimalField(decimal_places=2, default=0, help_text='用戶實際獲得的回饋金額', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Actual Reward Earned')),
                ('transaction_date', models.DateTimeField(verbose_name='Transaction Date')),
                ('source', models.CharField(choices=[('CHROME', 'Chrome 擴展偵測'), ('MANUAL', '用戶手動輸入')], default='CHROME', max_length=10, verbose_name='Transaction Source')),
                ('payment_method', models.CharField(choices=[('CREDIT', '信用卡'), ('WALLET', '數位錢包'), ('MOBILE', '行動支付')], default='CREDIT', max_length=10, verbose_name='Payment Method')),
                ('url', models.URLField(blank=True, help_text='用戶購物時的頁面 URL', verbose_name='Shopping Page URL')),
                ('page_title', models.CharField(blank=True, help_text='購物頁面的標題', max_length=200, verbose_name='Page Title')),
                ('was_recommended', models.BooleanField(default=False, help_text='系統是否有推薦此卡片', verbose_name='System Recommended')),
                ('used_recommended_card', models.BooleanField(default=False, help_text='用戶是否使用了系統推薦的卡片', verbose_name='Used Recommended Card')),
                ('potential_reward_missed', models.DecimalField(decimal_places=2, default=0, help_text='如果使用推薦卡片可以獲得的額外回饋', max_digits=8, verbose_name='Potential Reward Missed')),
                ('category', models.CharField(blank=True, help_text='自動識別或手動分類的消費類型', max_length=20, verbose_name='Spending Category')),
                ('tags', models.JSONField(default=list, help_text='額外的分類標籤，如：特價、節慶促銷等', verbose_name='Tags')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record Time')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_transactions', to='cards.creditcard', verbose_name='Credit Card Used')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_transactions', to='merchants.merchant', verbose_name='Merchant')),
                ('recommended_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_transactions', to='cards.creditcard', verbose_name='System Recommended Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Online Transaction',
                'verbose_name_plural': 'Online Transactions',
                'db_table': 'online_transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['user', '-transaction_date'], name='online_trans_user_date_idx'), models.Index(fields=['merchant', '-transaction_date'], name='online_trans_merchant_date_idx'), models.Index(fields=['card', '-transaction_date'], name='online_trans_card_date_idx'), models.Index(fields=['source', '-transaction_date'], name='online_trans_source_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='RewardCalculationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='預計算的金額，如：100, 500, 1000, 2000, 5000', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Spending Amount')),
                ('calculated_reward', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Calculated Reward')),
                ('reward_rate', models.DecimalField(decimal_places=2, help_text='百分比形式的回饋率', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reward Rate')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Calculation Time')),
                ('is_valid', models.BooleanField(default=True, help_text='回饋規則變更時會標記為無效', verbose_name='Calculation Valid')),
                ('last_used', models.DateTimeField(blank=True, help_text='記錄此快取最後被使用的時間', null=True, verbose_name='Last Used Time')),
                ('usage_count', models.IntegerField(default=0, help_text='此快取被使用的總次數', verbose_name='Usage Count')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_calculations', to='cards.creditcard', verbose_name='Credit Card')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_calculations', to='merchants.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Reward Calculation Cache',
                'verbose_name_plural': 'Reward Calculation Caches',
                'db_table': 'reward_calculation_cache',
                'ordering': ['-calculation_date'],
                'indexes': [models.Index(fields=['merchant', 'amount', 'is_valid'], name='cache_merchant_amount_idx'), models.Index(fields=['card', 'is_valid'], name='cache_card_valid_idx'), models.Index(fields=['is_valid', '-last_used'], name='cache_valid_used_idx')],
                'unique_together': {('merchant', 'card', 'amount')},
            },
        ),
        migrations.CreateModel(
            name='UserSpendingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('total_online_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Online Spending')),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Rewards Earned')),
                ('total_rewards_missed', models.DecimalField(decimal_places=2, default=0, help_text='使用推薦卡片可獲得的額外回饋', max_digits=8, verbose_name='Total Rewards Missed')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='Transaction Count')),
                ('chrome_detected_transactions', models.IntegerField(default=0, help_text='由 Chrome 擴展自動偵測的交易數量', verbose_name='Chrome Detected Transactions')),
                ('recommendations_shown', models.IntegerField(default=0, help_text='Chrome 擴展顯示推薦的次數', verbose_name='Recommendations Shown')),
                ('recommendations_followed', models.IntegerField(default=0, help_text='用戶採用推薦的次數', verbose_name='Recommendations Followed')),
                ('merchant_spending', models.JSONField(default=dict, help_text='各購物網站的消費統計：{"shopee.tw": 15000, "momo.com.tw": 8500}', verbose_name='Merchant Spending Statistics')),
                ('category_spending', models.JSONField(default=dict, help_text='各消費分類的金額統計：{"electronics": 20000, "clothing": 5000}', verbose_name='Category Spending Statistics')),
                ('card_usage', models.JSONField(default=dict, help_text='各卡片的使用統計：{"card_1": {"amount": 15000, "transactions": 25}}', verbose_name='Card Usage Statistics')),
                ('payment_methods', models.JSONField(default=dict, help_text='各種支付方式的使用統計', verbose_name='Payment Methods Statistics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_patterns', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Spending Pattern',
                'verbose_name_plural': 'User Spending Patterns',
                'db_table': 'user_spending_patterns',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['user', '-year', '-month'], name='patterns_user_date_idx')],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Statistics Date')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Total Transactions')),
                ('total_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Transaction Value')),
                ('unique_users', models.IntegerField(default=0, verbose_name='Unique Users')),
                ('chrome_extension_views', models.IntegerField(default=0, help_text='Chrome 擴展在此網站的顯示次數', verbose_name='Chrome Extension Views')),
                ('recommendation_clicks', models.IntegerField(default=0, help_text='用戶點擊推薦卡片的次數', verbose_name='Recommendation Clicks')),
                ('most_used_cards', models.JSONField(default=dict, help_text='在此網站最常使用的卡片統計', verbose_name='Most Used Cards')),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Average Transaction Value')),
                ('average_reward_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Average Reward Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='merchants.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Website Analytics',
                'verbose_name_plural': 'Website Analytics',
                'db_table': 'website_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['merchant', '-date'], name='website_analytics_idx'), models.Index(fields=['-date'], name='website_analytics_date_idx')],
                'unique_together': {('merchant', 'date')},
            },
        ),
    ]
