# Generated by Django 5.2.5 on 2025-08-20 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('cards', '0002_alter_creditcard_options_alter_creditcard_annual_fee_and_more'),
        ('merchants', '0002_alter_merchant_options_alter_merchant_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rewardcalculationcache',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userspendingpattern',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='websiteanalytics',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rewardcalculationcache',
            constraint=models.UniqueConstraint(fields=('merchant', 'card', 'amount'), name='unique_merchant_card_amount'),
        ),
        migrations.AddConstraint(
            model_name='userspendingpattern',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_user_year_month'),
        ),
        migrations.AddConstraint(
            model_name='websiteanalytics',
            constraint=models.UniqueConstraint(fields=('merchant', 'date'), name='unique_merchant_date'),
        ),
    ]
